import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import NavbarComponent from "@/components/navbar";
import { OpenSans } from "@next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const openSans = OpenSans

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <div className="w-full bg-radial-space h-screen">
          <NavbarComponent />
            <Image 
                className="w-full"
                src={"/images/stars.svg"}
                alt="stars"
                layout="fill"
                objectFit="cover"
            />
            {children}
        </div>
      </body>
    </html>
  );
}
